{"name": "Проверка ошибки при авторизации с неверным логином или паролем", "status": "passed", "parameters": [{"name": "field", "value": "'password'"}], "start": 1701623483549, "stop": 1701623483592, "uuid": "dcf9c6f2-0e4c-4a58-9d8a-964fc237b7b3", "historyId": "ef4353ceb8d682b16af71b9c81b2e699", "testCaseId": "4db5d0b446ab9c4f6b27d7c467c0f18e", "fullName": "tests.test_login#test_login_courier_with_invalid_log_or_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "B-F2027P7V-0432.local"}, {"name": "thread", "value": "82330-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}